gpu_index: 0


def args_input():
    p = argparse.ArgumentParser(description='cmd parameters')
    ##common argument
    p.add_argument('--gpu_index', '-gpu_index', type=int, default=0)
    p.add_argument('--defaults_path', '-defaults_path', type=str, default='/home/kanghyun/Monai_Femoral_Artery')
    p.add_argument('--model_name', '-model_name', type=str, default= 'UNet', help="model list of UNet, UNETR, SwinUNETR, UNet_Multiheader")
    p.add_argument('--loss_function_name', '-loss_function_name', type=str, default= 'DiceLoss', help="loss function list of DiceLoss, DiceCELoss, DiceFocalLoss, SoftclDiceLoss, FGDTMloss")
    p.add_argument('--optimizer_name', '-optimizer_name', type=str, default= 'Adam', help = 'optimizer list of Adam, AdamW')
    p.add_argument('--cache_rate', '-cache_rate', type=float, default= 1.0)
    p.add_argument('--num_workers', '-num_workers', type=float, default= 4)
    p.add_argument('--set_determinism_seed', '-set_determinism_seed', type=float, default= 4)

    ## UNet argument
    p.add_argument('--max_epochs', '-max_epochs', type=int, default= 100)
    p.add_argument('--val_interval', '-val_interval', type=int, default= 2)

    ## SwinUNETR argument
    p.add_argument('--cache_num', '-cache_num', type=int, default= 30)
    p.add_argument('--num_samples', '-num_samples', type=int, default= 4)
    # p.add_argument('--split_json', '-split_json', type=str, default= 'dataset_spleen/dataset_spleen.json')
    p.add_argument('--split_json', '-split_json', type=str, default= 'data/femoral/dataset_femoral_all_case.json')
    p.add_argument('--max_iterations', '-max_iterations', type=int, default= 30000)
    p.add_argument('--eval_num', '-eval_num', type=int, default= 500)
    p.add_argument('--to_onehot', '-to_onehot', type=int, default= None)
    ## distance_weight argument
    p.add_argument('--distance_map_weight', '-distance_map_weight', type=float, default= 1.0)
    p.add_argument('--dist_flag', '-dist_flag', type=int, default= 0)
